
path: '/content/gdrive/My Drive/Colab Notebooks/IIIT/SHRISHTI-24/Garbage_Identification' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: garbage
